SC packages delete function
nss-evening-cohort-19/gitsub-supersonic-wizardz pull request #41
Opened 2022-05-12 23:44 UTC by scamp925

- [ ] Open server and hard refresh
- [ ] Head over to packages
- [ ] Start by deleting a current card
- [ ] Create a new card then delete it
- [ ] ALSO what do you think of our page without borders and a black background?? Do you like the blue?

Please note: I will float the button right, so it will be in the upper righthand corner when I get to css

2022-05-12 23:51 UTC, PennCreative approved these changes

2022-05-12 23:58 UTC, shalane-proctor requested changes
Delete button is deleting first item only. Can you take a look?

2022-05-13 00:09 UTC, shalane-proctor approved these changes

2022-05-13 00:10 UTC, patrick24cr reviewed
Looks good

2022-05-13 00:11 UTC, merged